### ISSUE TITLE
Undocumented fields in user object

### ISSUE THREAD

**Issue by mpickering** [slackhq/slack-api-docs#11]
An "in the wild" user object contains a few more fields which aren't documented in the documentation.

- `status`
- `real_name_normalized`
- `is_bot`
- `title`
- `tz`, `tz_label`, `tz_offset`

`has_files` also doesn't appear in the response.

`skype` and `phone` are also repeated in the `user` object and `profile` object. Which one takes priority and why are they repeated?

**Comment by awalla** [comment]
Hello! As a quick update to this, we do still have these changes to our documentation on our to-do list—we've not forgotten about them. Thanks for your patience!

**Comment by drawks** [comment]
I'm confused why this issue is closed... I don't see any changes to address these issues.

**Comment by matthewmueller** [comment]
+1 it's unclear when `tz` is null and when it's set

**Comment by gasi** [comment]
👍 to documenting `real_name_normalized` vs `real_name`. Thanks.

**Comment by tyson-kubota** [comment]
The page https://api.slack.com/bot-users (all the way down) even contains instructions on using `user.is_bot` to ascertain bot status:

> You can tell if a user object returned by our API is a bot user by checking the is_bot property.

It might be nice to update the user object doc at https://api.slack.com/types/user accordingly.
