### ISSUE TITLE
Error codes lacking documentation

### ISSUE THREAD

**Issue by mpickering** [slackhq/slack-api-docs#12]
Thanks for your help so far. Is there a description of what the different error codes mean anywhere? For example it seems `1` corresponds to "Socket URL has expired" but I assume there are other undocumented codes as well?

```
{
    "type": "error",
    "error": {
        "code: 1,
        "msg": "Socket URL has expired"
    }
}
```

**Comment by billinghamj** [comment]
+1 need RTM error code documentation

**Comment by dblock** [comment]
Slack said they will not be updating that repo until they hire someone. We don't have to wait. I've pulled JSON files from https://github.com/slackhq/slack-api-docs into https://github.com/dblock/slack-api-ref, which I intend to maintain and kept JSON files only. Would love to get documented errors schema there.

**Comment by awalla** [comment]
Thanks for this! We've now made a note to add error code clarification to our API docs and we'll hopefully have them updated soon. We'll keep an eye on issues here in future, but if you have questions or feedback, you can also email us at feedback@slack.com for a speedier response. Thank you!
