### ISSUE TITLE
error":"bad_client_secret

### ISSUE THREAD

**Issue by sakaatrapidera** [slackhq/slack-api-docs#18]
Hello I am getting error as

"ok":false,"error":"bad_client_secret

for authentication after calling  https://slack.com/api/oauth.access api.

Any help would be appreciated.

Thanks 
Saka

**Comment by ernesto-jimenez** [comment]
Hi @sakaatrapidera,

How are you using it? Are you using an oauth2 library?

Make sure your library is sending the `client_secret` instead of setting up HTTP Basic Auth.

e.g: golang's oauth2 library doesn't pass on the client_secret, which produces the error you are getting.

```go
	v.Set("client_id", c.ClientID)
	bustedAuth := !providerAuthHeaderWorks(c.Endpoint.TokenURL)
	if bustedAuth && c.ClientSecret != "" {
		v.Set("client_secret", c.ClientSecret)
	}
	req, err := http.NewRequest("POST", c.Endpoint.TokenURL, strings.NewReader(v.Encode()))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	if !bustedAuth && c.ClientSecret != "" {
		req.SetBasicAuth(c.ClientID, c.ClientSecret)
	}

// [...]

// providerAuthHeaderWorks reports whether the OAuth2 server identified by the tokenURL
// implements the OAuth2 spec correctly
// See https://code.google.com/p/goauth2/issues/detail?id=31 for background.
// In summary:
// - Reddit only accepts client secret in the Authorization header
// - Dropbox accepts either it in URL param or Auth header, but not both.
// - Google only accepts URL param (not spec compliant?), not Auth header
func providerAuthHeaderWorks(tokenURL string) bool {
	if strings.HasPrefix(tokenURL, "https://accounts.google.com/") ||
		strings.HasPrefix(tokenURL, "https://github.com/") ||
		strings.HasPrefix(tokenURL, "https://api.instagram.com/") ||
		strings.HasPrefix(tokenURL, "https://www.douban.com/") ||
		strings.HasPrefix(tokenURL, "https://api.dropbox.com/") ||
		strings.HasPrefix(tokenURL, "https://api.soundcloud.com/") ||
		strings.HasPrefix(tokenURL, "https://www.linkedin.com/") {
		// Some sites fail to implement the OAuth2 spec fully.
		return false
	}

	// Assume the provider implements the spec properly
	// otherwise. We can add more exceptions as they're
	// discovered. We will _not_ be adding configurable hooks
	// to this package to let users select server bugs.
	return true
}
```

**Comment by malinkie** [comment]
Hi, I'm having a similar issue to @sakaatrapidera.

1. Hitting `https://slack.com/oauth/authorize?client_id=<CLIENTID>&redirect_uri=<URI>` in browser
2. Redirect collects the response `code`
3. Attempting
```
curl -i \
https://slack.com/api/oauth.access?client_id=<CLIENTID>&client_secret=<SECRET>&code=<CODE>&redirect_uri=<URI>
```

Response:
```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Encoding: gzip
Content-Type: application/json; charset=utf-8
Date: Thu, 30 Jul 2015 18:28:56 GMT
Server: nginx
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Content-Length: 60
Connection: keep-alive

{ok: false, error: "bad_client_secret"}
```

I'm sure im missing something here... :)

**Comment by iamcal** [comment]
It might sound obvious, but are you sure you're sending the correct client secret that corresponds to the client ID?

**Comment by malinkie** [comment]
@iamcal Yeah, its the correct secret :) It is potentially my nginx config. Reviewing now.

**Comment by awalla** [comment]
Did you have any success after looking into your nginx config? If you're still seeing these errors, we'd be happy to help. And for a quicker response, you can send any questions to feedback@slack.com — we'll keep an eye on issues here but sending us an email will generally get you a faster reply.

**Comment by malinkie** [comment]
@awalla Got it going. Thanks. It was my nginx config gremlins.

**Comment by cihangir** [comment]
https://github.com/slackhq/slack-api-docs/issues/18#issuecomment-72201873 

Just a note,

Works fine with the latest OAuth package https://github.com/golang/oauth2

**Comment by ertdredge** [comment]
Hi, @ernesto-jimenez 

> Make sure your library is sending the `client_secret` instead of setting up HTTP Basic Auth.

Thanks for that now-ancient tip.  Got me sorted out.

- Ert
