### ISSUE TITLE
Type mismatches reported by users

### ISSUE THREAD

**Issue by mpickering** [slackhq/slack-api-docs#19]
Hi,

I've had two type mismatches reported to me by users. It would be very useful for me and other users if you could specify the types of all fields so that I can verify the correctness of my library.

mpickering/slack-api#9
mpickering/slack-api#6

**Comment by awalla** [comment]
Thanks for this! We've made a note of these two and will be able to take a look into both these issues. If you have any further questions or feedback for us, please feel free to send them to feedback@slack.com. We'll continue to monitor issues here, but our response time will generally be faster using that email address. Thanks again!
