### ISSUE TITLE
Audit API

### ISSUE THREAD

**Issue by jwilkins** [slackhq/slack-api-docs#20]
Some sort of auditing API is needed.   Team Settings/access logs and Account/access logs in the web interface have user login times/ip addresses but more than this is needed and should be programmatically available.  File access logs would be one example.

**Comment by jsquirrelz** [comment]
+1. A better ability for an owner/admin to grab account information would be great. Especially something like `integrations.list` that would return the number of integrations and what they are.

**Comment by awalla** [comment]
Thanks for these suggestions! We're working on better admin tools for integrations, and will make a note that you'd like to see some auditing API features in addition to the currents access logs. If you have any other suggestions, we'd be happy to hear them. We're going to continue monitoring issues here, but for a speedier reply, you can also email feedback@slack.com. Thanks again!
