### ISSUE TITLE
Trello integration Issue. Timezones

### ISSUE THREAD

**Issue by rstormsf** [slackhq/slack-api-docs#21]
Not sure where is the right place to post an Issue about it:
Steps:
1) Integrate Trello with Slack with notifications when a Due Date changes
2)Set Due date in Trello
3)Notice that Slack just shows default UTC from Trello, <b>IGNORING</b> user's settings for Timezone(UTC -8) in my case

**Comment by kaykim** [comment]
+1

**Comment by nulogyian** [comment]
+1

**Comment by rstormsf** [comment]
It looks like it's Slack issue:
https://twitter.com/rstormsf/status/567917305033670656

**Comment by kaykim** [comment]
@rstormsf Good job! Thank you!

**Comment by awalla** [comment]
Thanks for flagging this, and for your patience! We released a fix for this a little while ago so the integration should now respect your timezone settings. If not, let us know!
