### ISSUE TITLE
Embedded message in message_changed subtype may not have a user

### ISSUE THREAD

**Issue by jtatum** [slackhq/slack-api-docs#27]
The api documentation for message_changed lists an embedded message with a user attribute, however, if the original message didn't have one, the message_changed message won't, either. This sounds obvious but the docs should probably reflect it somehow.

Example scenario: when a bot_message is unfurled, the server emits a message_changed event.

**Comment by awalla** [comment]
Thanks for this, and for your patience! We've made a note of it and it's on our to-do list.
