### ISSUE TITLE
Create endpoint for adding new emoji

### ISSUE THREAD

**Issue by xytxytxyt** [slackhq/slack-api-docs#28]
So that we can add new emoji in a one-time batch.

**Comment by jerhinesmith** [comment]
:+1:

I'm trying to upload team-based emoji (e.g. NBA teams, NFL teams, etc.), and it would be super useful to not have to do these through the web UI.

**Comment by inkel** [comment]
Yes please. This would be really useful.

**Comment by judemelancon** [comment]
I also wish for this feature.

**Comment by smashwilson** [comment]
I actually hacked up [slack-emojinator](https://github.com/smashwilson/slack-emojinator) as a way to do batch emoji addition just by automating the form upload, but it's (1) it's kind of terrible and (2) I'm pretty sure it's broken right now.

If anyone has the bandwidth to patch it up I will happily accept PRs and/or interested collaborators :wink: It's written in Python.

**Comment by grundleborg** [comment]
@smashwilson your script seems to be working fine - I just used it to upload a bunch of emoji - nice work!

**Comment by austinemayer** [comment]
I have been trying to batch upload animated gif pokemon sprites. I can not seem to get anything to go through. Do we know if this still works?

**Comment by awalla** [comment]
Thanks for the votes for this! We have seen previous requests for bulk uploading emoji and it's something that's on the to-do list. It's a long list so we don't have a timeline, but we do know it would be greatly appreciated. 
For any other suggestions you might have, you can also get in touch with us at feedback@slack.com. We'll be keeping an eye on issues here, but we'll generally be able to get you a speedier reply from there. Thanks again!

**Comment by cmoine** [comment]
+1 for this feature

**Comment by gileswells** [comment]
+1 of course but also for new people to this thread @smashwilson's [slack-emojinator](https://github.com/smashwilson/slack-emojinator) is functional and a way around this limitation for the time being.

**Comment by lambtron** [comment]
I, too, was frustrated at this, so I wrote https://github.com/lambtron/emojipacks as well as http://www.emojipacks.com/ to solve for this!

**Comment by MaitreyaBuddha** [comment]
+1 to this feature.
Also, how can you close an issue when "it's something that's on the to-do list"? That means it's still open, as far as any task system I have ever known.

**Comment by matt-oakes** [comment]
👍 for this feature as well.

The use-case I am thinking of is less about "bulk adding" and more about adding a special emoji when a bot is added to the Slack team which users can use in reactions and the bot can use in its messages.

**Comment by dumptyd** [comment]
+2 for this feature.

**Comment by patcon** [comment]
YES! Our use-case would be writing a hubot command that will allow team members to easily add emoji from an image url (complete with auto-resizing)

i imagine emojipacks code will help me make a little service in the meantime. Thanks @lambtron!

**Comment by mjambon** [comment]
For our application, we'd like API support for custom emojis so that our bot could use appropriate icons in all situations. It's a concise way of signaling the nature of a message or the role of a button, and there's not always a good emoji that describes what we want.

**Comment by andrhamm** [comment]
Please.

**Comment by infn8** [comment]
+1 * ∞

**Comment by joaomarcelofm** [comment]
+1  please, needed by next monday

**Comment by gileswells** [comment]
@joaomarcelofm good luck with that. This thread has been open for over 2and a half years.

**Comment by gileswells** [comment]
https://github.com/smashwilson/slack-emojinator

Workable alternative and honestly easier than why it would take to implement an api.

**Comment by joaomarcelofm** [comment]
@gileswells yeah, I'm looking into it already, but thanks man! :)
and the deadline stuff was just a little joke with my project mates

**Comment by philihp** [comment]
would love to see this happen.

**Comment by Artemnsk** [comment]
Really want to have it.
https://github.com/smashwilson/slack-emojinator is not alternative - that is awful to ask user to provide your app with browser cookies to install emojis needed for Slack app.
Furthermore emoji could be deleted manually by admin of Slack team and that could broke app UI.

**Comment by jufemaiz** [comment]
Hi Slackers,
would just like to say including the ability to create emojis via the API would be a great step.

Cheers, Joel

**Comment by jakebathman** [comment]
For anyone needing bulk upload (until Slack adds an endpoint), I've been using this chrome extension for a while and it's great: https://chrome.google.com/webstore/detail/neutral-face-emoji-tools/anchoacphlfbdomdlomnbbfhcmcdmjej

**Comment by jackellenberger** [comment]
This is now "solved" - `/api/emoji.add` is now a proper api endpoint that accepts user tokens and multipart form uploads, no user crumb / browser cookie required. 

👍 for neutral face emoji, it is perfect for uploading multiple emoji at a time (and hey make a bunch at a time with teaas.fyi !)

I have written https://github.com/jackellenberger/emojme to do more `bulk` tasks, like migrating emoji across slack instances, syncing emoji between multiple instances, uploading emoji to multiple instances at once, and backing up existing emoji. Enjoy!

**Comment by Artemnsk** [comment]
Honestly I was sure they add something more sophisticated e.g.
1. To take care of emoji name conflicts (emoji name is already taken by other custom/default emoji)
2. To not allow to remove emoji if it is is "a part of your Slack app" otherwise user with admin rights can (accidentally?) remove you custom emoji and break your Slack app UI.

Seems this api call is not documented yet (https://api.slack.com/methods#emoji). I suppose there will be extra permission available for bot user to add new emojis so my bot can do it during app installation? Hopefully on this stage we can take care of possible name conflicts and add extra "number" suffix to resolve conflict or something..

Anyway the best day of my life 😢

**Comment by jackellenberger** [comment]
@Artemnsk re: concern # 1, [emojme](https://github.com/jackellenberger/emojme/pull/7) now deals with name conflicts if you pass `--avoidCollisions` to either `add` or `upload`
![](https://github.com/jackellenberger/allmyemojichildren/blob/master/emoji/bongocat-keeb.gif?raw=true)

No news yet whether bots will ever have the power to muck with emoji, but i'm praying for the day.

**Comment by ckasabula** [comment]
With undocumented `/api/emoji.add`, getting `not_allowed_token_type`. have tried bot token `xoxb` and legacy token `xoxp`. Any ideas?

**Comment by jackellenberger** [comment]
@ckasabula it's user tokens only for the time being, `xoxs`.

**Comment by ckasabula** [comment]
Thanks @jackellenberger. Figured that out shortly after I posted. Was going to post this morning but you beat me to it.

**Comment by jackellenberger** [comment]
@pprus https://github.com/jackellenberger/emojme#finding-a-slack-token
User tokens are present on every logged in slack page, for the time being.

**Comment by qqhann** [comment]
It's 7 years ago...
