### ISSUE TITLE
channels.list method does not return full channel objects

### ISSUE THREAD

**Issue by canol** [slackhq/slack-api-docs#29]
channel.list method is said to be returning channel objects but the json response does not include fields like *last_read*, *latest*, *unread_count*, *unread_count_display* which is present in channel type page of documentation.

This is also true for groups.list and im.list. They don't return full group and im types.

**Comment by iamcal** [comment]
those values are only included when connecting to the real-time service, because of synchronization. we should update the docs to explain this.

**Comment by canol** [comment]
I see, thank you...I see, Thank you...
