### ISSUE TITLE
chat.history timestamp

### ISSUE THREAD

**Issue by fredpedro** [slackhq/slack-api-docs#31]
I wonder how the 'ts'(timestamp) of each messages in a chat.history method is being read, or is humanly readable.

**Comment by ernesto-jimenez** [comment]
ts is an identifier and it's unique per channel. The part before the dot is a Unix timestamp and the part after the dot is used to keep the message order.

**Comment by fredpedro** [comment]
So there is no means of knowing the date and time of a particular message?

**Comment by fredpedro** [comment]
Thank you!, makes much sense now.

**Comment by awalla** [comment]
Thanks for jumping in to help, Ernesto! 
We'll be continuing to monitor issues here, but for a faster reply time in future, you can also contact us with any questions or issues using feedback@slack.com.
