### ISSUE TITLE
Docs say RTM supports message formatting, but apparently do not

### ISSUE THREAD

**Issue by DanTup** [slackhq/slack-api-docs#32]
In the [RTM docs](https://api.slack.com/rtm), it says:

> The RTM API only supports posting simple messages formatted using our [default message formatting mode](https://api.slack.com/docs/formatting).

The first thing on the linked page is for URLs. However, I was [unable to make this work](https://twitter.com/DanTup/status/624637922994688000) and got [the response](https://twitter.com/SlackHQ/status/624641772610826240):

> Sorry, the RTM API doesn't support formatted links. Try the chat.postMessage API method instead.

This should be clarified in the docs. I spent some time debugging before realising it wasn't my code, and I suspect others might do the same.

(Or, even better, add support for it and make the API match the docs)

**Comment by clintkelly** [comment]
:+1: I just spent about an hour trying to get links to work before I found this issue.

**Comment by awalla** [comment]
Thanks for bringing this up, and sorry for the hassle! This is on our list to improve and clarify in our documentation. If there's anything else we can help with, we'll be keeping an eye on issues here, but for a generally quicker response, we're also at feedback@slack.com. Thanks again!

**Comment by zackify** [comment]
Why did this get closed. I also just wasted an hour.

**Comment by dcsan** [comment]
looks like @awalla is a bot, other issues are closed without them actually be fixing and the same message added.

**Comment by mccreath** [comment]
@zackify @dcsan As awalla mentioned (who is one of our support agents, and not a bot), we keep an eye on things here, but we don't actively do support here. Your best bet for questions about the API is emailing feedback@slack.com.

The most up-to-date version of the docs are at https://api.slack.com/. This repo is updated regularly from that. We will get the formatting info for the RTM API looked at tomorrow. Thanks for bringing it up.

**Comment by zackify** [comment]
The bot doesn't seem to get it's text formatted when sending replies. I'm
using the new botkit. I'm really liking it! :)
