### ISSUE TITLE
escape chars are handled strange when inserted before text modifiers

### ISSUE THREAD

**Issue by michaelperret** [slackhq/slack-api-docs#34]
![screen shot 2015-07-31 at 2 25 19 pm](https://cloud.githubusercontent.com/assets/1673044/9018060/04e7bdfc-3790-11e5-8b3c-026ca409cf49.png)

**Comment by awalla** [comment]
Thanks for this! The backslash won't escape the formatting, I'm afraid. You can prevent the formatting by using single or triple backticks to enclose the message. You can also prevent it by adding a space on either side of the formatting character: `\ * stuff in asterisks \ *`. I hope that helps! 
If you have any feedback or questions in future, we can be reached at feedback@slack.com. We'll be monitoring issues here, but sending an email will generally result in a quicker reply from us. Thanks!
