### ISSUE TITLE
Timestamps are sometimes numbers and sometimes strings

### ISSUE THREAD

**Issue by davedelong** [slackhq/slack-api-docs#35]
When I receive back a Channel object, the "created" field is a number.

However, when I receive back a Message object, the "ts" (which I assume means "timestamp") value is a *string*. It should also be sent as a number. Timestamps are not strings.

**Comment by ernesto-jimenez** [comment]
@davedelong this is a duplicate of #7 :)

**Comment by davedelong** [comment]
Yep!
