### ISSUE TITLE
Publish types schema

### ISSUE THREAD

**Issue by dblock** [slackhq/slack-api-docs#37]
I would expect types to be similar to methods, with documented fields and well known structure. At the very least would love to have .json files for each type so we can generate classes based on types in https://github.com/dblock/slack-ruby-client. 

Related: https://github.com/dblock/slack-ruby-client/issues/4

**Comment by Inumedia** [comment]
Agreed, this would significantly help improve my C# API and help with preventing my typed objects becoming out of date. This has caused some confusion when trying to update or add objects to my API at different points in time.

https://github.com/inumedia/slackapi

**Comment by dblock** [comment]
@lnumedia Slack said they will not be updating that repo until they hire someone. We don't have to wait. I've pulled JSON files from https://github.com/slackhq/slack-api-docs into https://github.com/dblock/slack-api-ref, which I intend to maintain and kept JSON files only. Would you like to contribute a types schema?

**Comment by awalla** [comment]
Thanks for the suggestion! We've made a note of this and added it to our to-do list. We'll not have this updated immediately but we now have it on our list so we'll hopefully have an update before too long. Thank you again!
