### ISSUE TITLE
Undocumented scope permissions

### ISSUE THREAD

**Issue by thesmart** [slackhq/slack-api-docs#42]
I've noticed that Intercom.com's slack integration allows for posting to a channel without read access. This doesn't appear to be anywhere in the API documentation.  What is the way to do this using oauth?  

<img width="619" alt="authorize_access_slack" src="https://cloud.githubusercontent.com/assets/280877/9794106/dcd1cf94-57ae-11e5-9d44-249eac2b8fdb.png">

**Comment by ernesto-jimenez** [comment]
@thesmart check the "Add to Slack" docs: https://api.slack.com/docs/slack-button

**Comment by thesmart** [comment]
@ernesto-jimenez Thanks! Probably should also be in https://api.slack.com/docs/oauth.  I didn't think to look for "a button", but this solves my issue.
