### ISSUE TITLE
`users.counts` method does not appear on docs site

### ISSUE THREAD

**Issue by benhartley** [slackhq/slack-api-docs#51]
I see a reference in this repository to a [`users.counts` method](https://github.com/slackhq/slack-api-docs/blob/master/methods/users.counts.md), yet it does not appear on [the docs site](https://api.slack.com/methods)

**Comment by ernesto-jimenez** [comment]
This repo is out of sync with the official documentation. Refer to https://api.slack.com :)




On Sun, Apr 10, 2016 at 1:56 PM -0700, "Benedict Hartley" <notifications@github.com> wrote:












I see a reference in this repository to a users.counts method, yet it does not appear on the docs site

**Comment by benhartley** [comment]
OK thanks, I guess I was hoping it was the other way around as that method does exactly what I need. I assume it has been deprecated, never mind....
