### ISSUE TITLE
Image link broken

### ISSUE THREAD

**Issue by shashwatbhatt** [slackhq/slack-api-docs#56]
In this pages
1) https://github.com/slackhq/slack-api-docs/blob/master/index_bot_users.md the image of conversation between bot and user
2) https://github.com/slackhq/slack-api-docs/blob/master/page_slack_button.md 
3) https://github.com/slackhq/slack-api-docs/blob/master/index_custom_integrations.md
are having a broken links.

**Comment by episod** [comment]
Thanks for flagging this!

For the canonical representation of these docs, including the images referenced in them, please see api.slack.com. Documentation in this repo is generated from that set and the image references and links contained with them are intended for their official representation.

You can find these specific docs there as:
1) https://api.slack.com/bot-users 
2) https://api.slack.com/docs/slack-button 
3) https://api.slack.com/custom-integrations
