### ISSUE TITLE
Message Event Clarification

### ISSUE THREAD

**Issue by mpickering** [slackhq/slack-api-docs#6]
Specifically referring to the [message type](https://api.slack.com/events/message), which fields are required and which are optional? 

One thing I found particularly confusing was this sentence (in [message_changed](https://api.slack.com/events/message/message_changed))

> The message property contains the updated message object.

In the example and my in the wild tests, it appears that the `message` object does not contain a (necessary) `channel` field so is a different kind of object. Would it be possible to clarify this point in the documentation?

**Comment by mccreath** [comment]
In the case of `message_changed`, the channel should be in the parent `message` object. In the case of the `star_removed` and `star_added` types, the `channel` is part of the `item` property, which is explained here: https://api.slack.com/methods/stars.list
