### ISSUE TITLE
Conflicting information on text in attachments

### ISSUE THREAD

**Issue by dmitriid** [slackhq/slack-api-docs#60]
## Issue

Documentation contradicts itself

> https://api.slack.com/docs/message-formatting#message_formatting
>
>> By default bot message text will be formatted, but attachments are not.
>

vs.

> https://api.slack.com/docs/message-attachments
>
>> *text*
>> This is the main text in a message attachment, and can contain standard message markup.

## What happens

Text in attachments is displayed non-formatted despite what documentation for attachments says. This can be tested using the provided message builder (minimal [example](https://api.slack.com/docs/messages/builder?msg=%7B%22attachments%22%3A%5B%7B%22fallback%22%3A%22Required%20plain-text%20summary%20of%20the%20attachment.%22%2C%22color%22%3A%22%2336a64f%22%2C%22text%22%3A%22*Optional*%20~text~%20_that_%20appears%20%60within%60%20the%20attachment%22%7D%5D%7D))

## What should happen

One of:

1. Documentation for message formatting should include details on how to enable text formatting in attachments. If not possible with current API, API should be updated to enable this

2. Documentation on attachments should include a note saying when and how text is formatted in attachments.

**Comment by ernesto-jimenez** [comment]
It is documented :)
From your first link:
> By default bot message text will be formatted, but attachments are not. To disable formatting on a non-user message, set the mrkdwn property to false. To enable formatting on attachment fields, set the mrkdwn_in array on each attachment to the list of fields to process. Some examples:

Your second link points to the first one for message formatting.



On Mon, Aug 8, 2016 at 8:53 AM +0100, "dmitriid" <notifications@github.com> wrote:










Issue



Documentation contradicts itself




https://api.slack.com/docs/message-formatting#message_formatting




By default bot message text will be formatted, but attachments are not.





vs.




https://api.slack.com/docs/message-attachments




text

This is the main text in a message attachment, and can contain standard message markup.



What happens



Text in attachments is displayed non-formatted despite what documentation for attachments says. This can be tested using the provided message builder (minimal example)

What should happen



One of:




Documentation for message formatting should include details on how to enable text formatting in attachments. If not possible with current API, API should be updated to enable this


Documentation on attachments should include a note saying when and how text is formatted in attachments.

**Comment by dmitriid** [comment]
Ah. Ooops :)

**Comment by dmitriid** [comment]
Thank you!

**Comment by ahaverty** [comment]
Also got confused about field formatting. A reference to the `mrkdwn_in` in the **fields** documentation would have been handy 🙌
