### ISSUE TITLE
How to get the message if i have message's channel and timestamp

### ISSUE THREAD

**Issue by wiyr** [slackhq/slack-api-docs#66]
How to get the message if i have message's channel and timestamp ? Is there any api to solve this problem ? I don't want to get all the channel message and compare their timestamp. And I find that method `search` and `reactions.list` don't have time filter. Is there any approach to find the message or reaction with specific duration ?

**Comment by episod** [comment]
For questions about the API itself, I strongly recommend reaching out to Slack's developer support team at feedback@slack.com.

The `channels.history` API method is probably your best bet for finding specific messages, as there's no direct retrieve-single-message API available. Use the `latest` and `oldest` parameters to focus the query on the specific timestamp you're looking for: https://api.slack.com/methods/channels.history
