### ISSUE TITLE
Question on Message formatting

### ISSUE THREAD

**Issue by itsmejainh** [slackhq/slack-api-docs#75]
Hi - 

I am referring to - https://api.slack.com/docs/message-formatting

I have bot who will be monitoring messages on a particular channel. Bot's duty would be to format messages posted by Users when specific conditions are met.

Is it possible for Bot to edit (prepend some formatting) user's messages through API. 

thank you.

**Comment by episod** [comment]
A bot user can only edit the messages the bot itself posts. Beyond bot user capabilities, you can utilize the user token. Asking for the `chat:write:user` scope will give you the ability to edit messages that the installing user posts using `chat.update`. To do this on behalf of multiple users you would need each team member to install the app with that scope and then your app would juggle between user access tokens, using the correlating token when updating a message authored by that user.

In the future, I recommend looking for support on the API & platform itself through our support team or community: https://api.slack.com/support

Best,
Taylor
