### ISSUE TITLE
rtm.start ~> team.icon.image_default: "1"

### ISSUE THREAD

**Issue by srhb** [slackhq/slack-api-docs#79]
According to [the docs](https://api.slack.com/methods/rtm.start), 

> If a team has not yet set a custom icon, the value of` team.icon.image_default` will be `true`.

However, what I'm receiving on a newly created workspace is `"image_default": "1"`

mpickering/slack-api#78

**Comment by morozgrafix** [comment]
Thank you for reporting it. It seems that it was a bug on our end and we have pushed the fix to make sure `boolean` value is returned for `rtm.start` as well as `team.info` methods.

Thanks.

**Comment by morozgrafix** [comment]
@mccreath @Roach I think it's safe to close this.
