### ISSUE TITLE
Channels.history response message timestamp

### ISSUE THREAD

**Issue by dominikeinkemmer** [slackhq/slack-api-docs#82]
Hi,

I'm currently trying to develop a bot for our organization that parses messages of a channel to extract date information from a channels messages. However, in order to do that I sometimes need a references date (to extract dates from strings like `tomorrow`, etc.).

The issue I have is that the `ts` field of the response from `channels.history` is not a proper timestamp but the unique message identifier (if I read that correctly #7 ) so I can't get the created date for the message. Is there anyway that I can extract the correct timestamp from the `ts` field or get the created-timestamp in any other way?

Thanks in advance.

**Comment by namedgraph** [comment]
So what was the solution here?
